import Head from "next/head";
import Header from "@/common/components/Header";
import Footer from "@/common/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>


      <Footer/>
    </>
  );
}
